#!/usr/bin/env python
# coding: utf-8

"""
GeoqApi.py
Copyright 2015 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from .. import configuration
from ..api_client import ApiClient

class GeoqApi(object):

    def __init__(self, api_client=None):
        if api_client:
            self.api_client = api_client
        else:
            if not configuration.api_client:
                configuration.api_client = ApiClient('http://localhost/MediaQ_MVC_V3/api')
            self.api_client = configuration.api_client
    
    
    def rectangle_query(self, swlat, swlng, nelat, nelng, **kwargs):
        """
        Returns a set of videos
        Returns a set of video locations with corresponding time and link to mediaq

        :param str swlat: South-West Latitude (required)
        :param str swlng: South-West Longitude (required)
        :param str nelat: North-East Latitude (required)
        :param str nelng: North-East Longitude (required)
        
        :return: str
        """
        
        # verify the required parameter 'swlat' is set
        if swlat is None:
            raise ValueError("Missing the required parameter `swlat` when calling `rectangle_query`")
        
        # verify the required parameter 'swlng' is set
        if swlng is None:
            raise ValueError("Missing the required parameter `swlng` when calling `rectangle_query`")
        
        # verify the required parameter 'nelat' is set
        if nelat is None:
            raise ValueError("Missing the required parameter `nelat` when calling `rectangle_query`")
        
        # verify the required parameter 'nelng' is set
        if nelng is None:
            raise ValueError("Missing the required parameter `nelng` when calling `rectangle_query`")
        
        all_params = ['swlat', 'swlng', 'nelat', 'nelng']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method rectangle_query" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/geoq/rectangle_query'.replace('{format}', 'json')
        method = 'GET'

        path_params = {}
        
        query_params = {}
        
        if 'swlat' in params:
            query_params['swlat'] = params['swlat']
        
        if 'swlng' in params:
            query_params['swlng'] = params['swlng']
        
        if 'nelat' in params:
            query_params['nelat'] = params['nelat']
        
        if 'nelng' in params:
            query_params['nelng'] = params['nelng']
        
        header_params = {}
        
        form_params = {}
        files = {}
        
        body_params = None
        
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(['application/json', 'application/xml', 'text/html', 'text/xml'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='str', auth_settings=auth_settings)
        
        return response
        
    def sample_fovs(self, **kwargs):
        """
        Returns a set of video frames
        Returns metadata of individual video frames, from which it is possible to construct geospatial features of a video such as it's trajectory and coverage.

        
        :return: str
        """
        
        all_params = []

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method sample_fovs" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/geoq/sample_fovs'.replace('{format}', 'json')
        method = 'GET'

        path_params = {}
        
        query_params = {}
        
        header_params = {}
        
        form_params = {}
        files = {}
        
        body_params = None
        
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(['application/json', 'application/xml', 'text/html', 'text/xml'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='str', auth_settings=auth_settings)
        
        return response
        
    def sample_videos(self, **kwargs):
        """
        Returns a set of videos
        Returns a set of video locations with corresponding time and link to mediaq

        
        :return: str
        """
        
        all_params = []

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method sample_videos" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/geoq/sample_videos'.replace('{format}', 'json')
        method = 'GET'

        path_params = {}
        
        query_params = {}
        
        header_params = {}
        
        form_params = {}
        files = {}
        
        body_params = None
        
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(['application/json', 'application/xml', 'text/html', 'text/xml'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='str', auth_settings=auth_settings)
        
        return response
        
    def test_swagger(self, **kwargs):
        """
        Test
        Test

        
        :return: str
        """
        
        all_params = []

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method test_swagger" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/geoq/test_swagger'.replace('{format}', 'json')
        method = 'GET'

        path_params = {}
        
        query_params = {}
        
        header_params = {}
        
        form_params = {}
        files = {}
        
        body_params = None
        
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(['application/json', 'application/xml', 'text/html', 'text/xml'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='str', auth_settings=auth_settings)
        
        return response
        
    def video_metadata(self, videoid, **kwargs):
        """
        Returns a set of video frames
        Returns metadata of individual video frames, from which it is possible to construct geospatial features of a video such as it's trajectory and coverage.

        :param str videoid: VideoId (required)
        
        :return: str
        """
        
        # verify the required parameter 'videoid' is set
        if videoid is None:
            raise ValueError("Missing the required parameter `videoid` when calling `video_metadata`")
        
        all_params = ['videoid']

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s' to method video_metadata" % key)
            params[key] = val
        del params['kwargs']

        resource_path = '/geoq/video_metadata'.replace('{format}', 'json')
        method = 'GET'

        path_params = {}
        
        query_params = {}
        
        if 'videoid' in params:
            query_params['videoid'] = params['videoid']
        
        header_params = {}
        
        form_params = {}
        files = {}
        
        body_params = None
        
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(['application/json', 'application/xml', 'text/html', 'text/xml'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, method, path_params, query_params, header_params,
                                            body=body_params, post_params=form_params, files=files,
                                            response='str', auth_settings=auth_settings)
        
        return response
        









